# Config file for automatic testing at travis-ci.org
language: python
dist: xenial
cache: pip

addons:
  postgresql: "10"

env:
  global:
  - PGHOST=localhost
  - PGUSER=postgres
  - PYTEST_ADDOPTS="--cov-append"

matrix:
  include:

  - python: 3.6
    env:
      TOX_ENV: py36-unit-tests,py36-integration-tests,py36-acceptance-tests

  - python: 3.7
    env:
      TOX_ENV: py37-unit-tests,py37-integration-tests,py37-acceptance-tests

  - python: 3.7
    env:
      TOX_ENV: check-lint

  - python: 3.7
    env:
      TOX_ENV: docs

# Taken from https://github.com/travis-ci/travis-ci/issues/9624
before_install:
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
- sleep 1

install:
  - pip install tox codecov
  - tox --notest -e $TOX_ENV

script:
  - tox -e $TOX_ENV

after_success:
- codecov

deploy:
  provider: pypi
  user: __token__
  password:
    secure: "hqUrw49Q2jdZ9cYWvI6/1pL9lGGnbHIxGdQtFRFSDLS7DhvI48FwuPD4swxALJIDnCnz99NdpZ5hRDcn95TUhTnhNGCDBOqHkFnu17H1TMZGgq21vZpGABgBpJ26RezmIIL463VcGbwbI88uNR815hKUw1hA/AUGdT4cKseqk/icsMTFfZYijxfJO/sItprFxF63VXNIj8Xv4BAof94Lw1gJII+VzCBZ51eA3jisttjXxKufuhdqPcnSFLh3YQ1JvXoPv5W1V+yIMcAa4Sm+UaEPsY/UMMAixJSBFEUJtEaiOHE4IxJb2GZauLa5mDzQKS7pULBcAi1moBthxkK35DDzXwaM1FVM1pFeoCSeHy9sTUEGnayKMaHMeqrrq0qg1G8H7EUI/4l9TMJdQif/joLM8QS80F3Wdk9hUzCTU5fkn6xcZYdynAoFc3IYXBbAUkcVTlLX+FGFWFfXoNx/sUFRxM+vElPxGNNG7Es+rHCGjTXhAYm+7sMvcD/UWKyWWvwdQkHOhmLhrKwbb99Kescfy0Z4b3NxlERo1IgtzWQwTGgM6FwxMUQS89hHcCZm2Q0vSKiFJMHLMqoxSqCPcDTegF6HtjWSdHFtUArbe3nWOu5GBEz6kNOjdRBh8Czh6bcbHFqnsP42QNfH6mCTYJKCU/zTdLusJnVCUAh+v8Q="
  on:
    branch: master
    tags: true
